// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwcHgaIyIvtGOeQfsfy3jdx5_aZFoSx44',
    appId: '1:742683333598:web:5f6c11d1d7463a6c4a034f',
    messagingSenderId: '742683333598',
    projectId: 'egift-97b47',
    authDomain: 'egift-97b47.firebaseapp.com',
    storageBucket: 'egift-97b47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI9Xw5ZcSEyxNVK497L7hO_G6v58ebWhA',
    appId: '1:742683333598:android:8daf67aed75010a64a034f',
    messagingSenderId: '742683333598',
    projectId: 'egift-97b47',
    storageBucket: 'egift-97b47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF-l8pUOlZdCwWOPW_Hx8M9otj8hKuRgI',
    appId: '1:742683333598:ios:99b5a168206159884a034f',
    messagingSenderId: '742683333598',
    projectId: 'egift-97b47',
    storageBucket: 'egift-97b47.appspot.com',
    iosBundleId: 'com.izhak.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF-l8pUOlZdCwWOPW_Hx8M9otj8hKuRgI',
    appId: '1:742683333598:ios:99b5a168206159884a034f',
    messagingSenderId: '742683333598',
    projectId: 'egift-97b47',
    storageBucket: 'egift-97b47.appspot.com',
    iosBundleId: 'com.izhak.store',
  );
}
